Repository Guliveer/song-request, pull requests merged in 2025-05, with the labels that each got.

#89 Implement lazy loading for followers and following lists
  src/components/User_Panel/Followers.jsx
Labels: enhancement

#88 Added option to set emoji as avatar
  package-lock.json
  package.json
  src/components/User_Panel/Account.jsx
  src/components/User_Panel/Followers.jsx
  src/utils/actions.js
Labels: enhancement

#90 Top 3 songs podium
  package-lock.json
  package.json
  src/components/TopSongsOlympicPodium.jsx
  src/pages/index.js
Labels: design

#69 Admin panel
  src/components/AddSongForm.jsx
  src/components/SongCard.jsx
  src/pages/admin/index.js
Labels: feature

#99 Fix banned URL check when adding song
  src/components/AddSongForm.jsx
Labels: bug

#107 YouTube and Spotify API functionality
  src/components/AddSongForm.jsx
  src/components/SongCard.jsx
  src/pages/api/spotify-preview.js
  src/pages/api/spotify-track.js
  src/utils/spotify.js
Labels: feature
