Repository Guliveer/song-request, pull requests merged in 2025-04, with the labels that each got.

#43 Bug fixes, improvements & auth providers
  package-lock.json
  package.json
  src/components/AuthProviders.jsx
  src/components/Items.jsx
  src/components/SongCard.jsx
  src/pages/login/index.js
  src/pages/register/index.js
  src/pages/register/success.js
  src/styles/globals.css
  src/styles/theme.js
  src/utils/actions.js
Labels: bug, enhancement, feature

#45 Renamed AuthProviders component and fixed small mistakes
  src/components/AuthProvidersList.jsx
  src/pages/login/index.js
  src/pages/register/index.js
Labels: enhancement

#46 Pages titles and icons add
  public/favicon.ico
  public/favicon/apple-touch-icon.png
  public/favicon/favicon-96x96.png
  public/favicon/favicon.ico
  public/favicon/favicon.svg
  public/favicon/safari-pinned-tab.svg
  public/favicon/site.webmanifest
  public/favicon/web-app-manifest-192x192.png
  public/favicon/web-app-manifest-512x512.png
  src/components/SetTitle.jsx
  src/pages/_app.js
  src/pages/_document.js
  src/pages/admin/index.js
  src/pages/index.js
  src/pages/login/index.js
  src/pages/register/index.js
  src/pages/register/success.js
  src/pages/user/index.js
Labels: enhancement

#47 queue sorting
  src/components/Queue.jsx
Labels: feature

#49 Changed form UI & UX
  package-lock.json
  package.json
  src/components/AddSongForm.jsx
Labels: enhancement, design

#59 SearchField component add to queue
  package-lock.json
  package.json
  src/components/Queue.jsx
  src/components/SearchField.jsx
Labels: feature

#60 queue limit with pagination
  src/components/Queue.jsx
  src/utils/actions.js
Labels: feature

#61 Improved SongCard and Queue UIs
  src/components/Queue.jsx
  src/components/SongCard.jsx
  src/components/skeletons/SkeletonSongCard.jsx
  src/styles/globals.css
Labels: enhancement, design

#68 SearchField improvement
  src/components/Queue.jsx
  src/components/SearchField.jsx
Labels: enhancement

#70 UX improvements & dynamic user avatars
  package-lock.json
  public/audio/mixkit-correct-answer-tone-2870.wav
  public/audio/mixkit-fast-small-sweep-transition-166.wav
  public/audio/mixkit-modern-technology-select-3124.wav
  src/components/AddSongForm.jsx
  src/components/Items.jsx
  src/components/NavMenu.jsx
  src/components/SongCard.jsx
  src/context/UserContext.jsx
  src/pages/login/index.js
  src/pages/register/index.js
  src/utils/actions.js
Labels: enhancement, feature

#71 User Panel Functions
  src/components/AuthProvidersList.jsx
  src/components/User_Panel/Account.jsx
  src/components/User_Panel/Followers.jsx
  src/components/User_Panel/Providers.jsx
  src/pages/register/index.js
  src/pages/user/index.js
Labels: feature

#73 Enhances song card with user following and vote info
  src/components/SongCard.jsx
  src/utils/actions.js
Labels: feature
