Repository Guliveer/song-request, pull requests merged in 2025-06, with the labels that each got.

#118 Fix footer position
  package-lock.json
  package.json
  src/components/Footer.jsx
  src/pages/_app.js
  src/pages/index.js
Labels: bug

#120 Option to link providers in User Panel
  src/components/AuthProvidersList.jsx
  src/components/User_Panel/Providers.jsx
Labels: enhancement

#123 Auth providers moved & URL regex check added
  src/components/AddSongForm.jsx
  src/components/AuthProvidersList.jsx
  src/components/Items.jsx
  src/components/User_Panel/Providers.jsx
  src/utils/authProviders.js
  src/utils/spotify.js
  src/utils/whitelistedUrls.js
Labels: enhancement, feature

#125 Reset and Forgot password options
  src/components/User_Panel/Account.jsx
  src/pages/_app.js
  src/pages/login/index.js
  src/pages/reset-password/index.js
Labels: feature

#131 Playlist information page
  src/pages/playlist/[playlist]/info.js
Labels: feature

#130 Spotify playback functionality
  src/components/Items.jsx
  src/components/SongCard.jsx
  src/components/SpotifyPlayer.jsx
  src/components/User_Panel/Providers.jsx
  src/utils/spotify.js
Labels: feature
